// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Service from "./service.js";
export {
    Service
};

export {
    CreateWindowOptions,
    FileFilter,
    Layout,
    LayoutInfo,
    NotificationOptions,
    OpenDirectoryOptions,
    OpenFileOptions,
    SaveFileOptions,
    ScreenInfo,
    Service,
    SnapPosition,
    ThemeInfo,
    TileMode,
    TrayMenuItem,
    WSEventManager,
    Window,
    WindowInfo,
    WindowState,
    WorkArea,
    WorkflowType
} from "./models.js";

export type {
    WindowOption
} from "./models.js";
