// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Writer is the interface that wraps the basic Write method.
 * 
 * Write writes len(p) bytes from p to the underlying data stream.
 * It returns the number of bytes written from p (0 <= n <= len(p))
 * and any error encountered that caused the write to stop early.
 * Write must return a non-nil error if it returns n < len(p).
 * Write must not modify the slice data, even temporarily.
 * 
 * Implementations must not retain p.
 */
export type Writer = any;
