// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as crypt$0 from "../../../Enchantrix/pkg/crypt/models.js";

/**
 * HashType defines the supported hashing algorithms.
 * Re-exported from Enchantrix for convenience.
 */
export type HashType = crypt$0.HashType;
