// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Core defines the interface for the core runtime functionalities that the
 * help service depends on. This typically includes methods for performing
 * actions and accessing the application context.
 */
export type Core = any;

/**
 * Display defines the interface for a display service. The help service
 * uses this interface to check for the presence of a display module,
 * allowing it to function as an optional dependency.
 */
export type Display = any;
