// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages documentation windows.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * OpenDocsWindow opens a documentation window at the specified path.
 * The path is appended to the base URL to form the full documentation URL.
 */
export function OpenDocsWindow(path: string): $CancellablePromise<void> {
    return $Call.ByID(2514509460, path);
}

/**
 * SetBaseURL sets the base URL for documentation.
 */
export function SetBaseURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(1851990453, url);
}

/**
 * SetCore sets the core reference for accessing other services.
 */
export function SetCore(c: core$0.Core | null): $CancellablePromise<void> {
    return $Call.ByID(527529290, c);
}
