// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HashType defines the supported hashing algorithms.
 */
export enum HashType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * LTHN is a custom quasi-salted hashing algorithm.
     */
    LTHN = "lthn",

    /**
     * SHA512 is the SHA-512 hashing algorithm.
     */
    SHA512 = "sha512",

    /**
     * SHA256 is the SHA-256 hashing algorithm.
     */
    SHA256 = "sha256",

    /**
     * SHA1 is the SHA-1 hashing algorithm.
     */
    SHA1 = "sha1",

    /**
     * MD5 is the MD5 hashing algorithm.
     */
    MD5 = "md5",
};
