// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service manages the in-app help system. It handles the initialization
 * of the help content, interaction with the core runtime, and display
 * of the help window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Init initializes the service with its core dependencies. This method is
 * intended to be called by the dependency injection system of the application
 * to provide the necessary `Core` and `Display` implementations.
 */
export function Init(c: $models.Core, d: $models.Display): $CancellablePromise<void> {
    return $Call.ByID(2251945077, c, d);
}

/**
 * Show displays the main help window. If a `Display` service is available,
 * it sends an action to the core runtime to open the window. Otherwise, it
 * falls back to using the `wails3` application instance to create a new
 * window. This ensures that the help functionality is available even when
 * the `Snider/display` module is not in use.
 */
export function Show(): $CancellablePromise<void> {
    return $Call.ByID(401579614);
}

/**
 * ShowAt displays a specific section of the help documentation, identified
 * by an anchor. Similar to `Show`, it uses the `Display` service if available,
 * or falls back to a direct `wails3` implementation. The anchor is appended
 * to the URL, allowing the help window to open directly to the relevant
 * section.
 */
export function ShowAt(anchor: string): $CancellablePromise<void> {
    return $Call.ByID(3303047483, anchor);
}
