// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ACTION(msg: $models.Message): $CancellablePromise<void> {
    return $Call.ByID(652345721, msg);
}

export function Core(): $CancellablePromise<$models.Core | null> {
    return $Call.ByID(1479405872).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RegisterAction(handler: any): $CancellablePromise<void> {
    return $Call.ByID(1645232084, handler);
}

export function RegisterActions(...handlers: any[]): $CancellablePromise<void> {
    return $Call.ByID(110375909, handlers);
}

export function RegisterService(name: string, api: any): $CancellablePromise<void> {
    return $Call.ByID(1499511189, name, api);
}

export function Service(name: string): $CancellablePromise<any> {
    return $Call.ByID(1817142494, name);
}

// Private type creation functions
const $$createType0 = $models.Core.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
