// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

export class Core {
    "App": application$0.App | null;

    /** Creates a new Core instance. */
    constructor($$source: Partial<Core> = {}) {
        if (!("App" in $$source)) {
            this["App"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Core instance from a string or object.
     */
    static createFrom($$source: any = {}): Core {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("App" in $$parsedSource) {
            $$parsedSource["App"] = $$createField0_0($$parsedSource["App"]);
        }
        return new Core($$parsedSource as Partial<Core>);
    }
}

export type Message = any;

// Private type creation functions
const $$createType0 = application$0.App.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
